apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3fit
  newTag: 5e756d09e35d87740a4ec9b19a0625bb178407cd
- name: us.gcr.io/vcm-ml/fv3net
  newTag: 5e756d09e35d87740a4ec9b19a0625bb178407cd
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: 5e756d09e35d87740a4ec9b19a0625bb178407cd
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: 5e756d09e35d87740a4ec9b19a0625bb178407cd
